#!/bin/bash

echo "Indtast en liste af ord, adskilt af mellemrum:"
read -a ordliste # Læser en linje med input ind i et array

# Udskriver elementerne i arrayet, adskilt af newline, og sender dem til 'sort'
for ord in "${ordliste[@]}"; do
    echo "$ord"
done | sort

